# Generated by Django 2.2.5 on 2019-11-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191109_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
    ]
