# Generated by Django 2.2.5 on 2019-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20191120_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, verbose_name='Last message'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.TextField(blank=True, verbose_name='Topic'),
        ),
    ]
