# Generated by Django 2.2.5 on 2019-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20191121_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Chat name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, null=True, verbose_name='Last message'),
        ),
    ]
