# Generated by Django 2.2.5 on 2019-11-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20191126_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='topic',
        ),
    ]
