# Generated by Django 3.0 on 2019-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_remove_chat_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
