# Generated by Django 2.2.5 on 2019-11-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-added_at',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
