# Generated by Django 2.2.5 on 2019-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191109_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-added_at',)},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='type',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Video')], default=1),
        ),
    ]
