# Generated by Django 3.0 on 2019-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_auto_20191205_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='url',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(default='null', upload_to='attachments/'),
            preserve_default=False,
        ),
    ]
